services:
    # PostgreSQL database service
    db:
        container_name: db
        image: postgres:17-alpine
        restart: unless-stopped # Always restart unless stopped manually
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data # Makes the database persistent

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@gmail.com
            PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - 8080:80 # pgAdmin will be accessible at http://localhost:8080
        depends_on:
            - db
        volumes:
            - pgadmin-data:/var/lib/pgadmin

    backend:
        container_name: backend
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
            - NODE_ENV=production
        depends_on:
            - db

volumes:
    postgres-data:
    pgadmin-data:
